### ISSUE TITLE
Support for Spotify

### ISSUE THREAD

**Issue by jbrepogmailcom** [ericmatte/ad-media-lights-sync#28]
### Describe the bug

Hello in your description you do not have Spotify. Is it correct that Media Player Light Sync does not support Spotify? Thanks, Jan

**Comment by ericmatte** [comment]
Hi @jbrepogmailcom,

In the [Compatibility](https://github.com/ericmatte/ad-media-lights-sync#compatibility) section of the README, it is written:
> That said, it **has been tested and is working** with the following devices

That said, I can confirm that this **App is working** with the [Spotify](https://www.home-assistant.io/integrations/spotify/) integration.
Be aware thought that sometime the Spotify integration is slow to update. This is because of how the Spotify integration works and has nothing to do with this app.

I will update the readme and close this issue.
