### ISSUE TITLE
Add Brightness

### ISSUE THREAD

**Issue by thundergreen** [ericmatte/ad-media-lights-sync#3]
Your app is just awesome.. Like this I get like a pseudo anbilight for my TV. THe only thing is that at the moment it turn the light to 100% each time. Is there maybe a way to adjust brightness? Would be awesome

Thanks anyway for this great app!

Your fan!

P.S. works like a charm :)

**Comment by ericmatte** [comment]
Good idea.

I've just created a pull request with that functionality: https://github.com/ericmatte/ad-media-lights-sync/pull/4.

Basically, with this you will be able to use:
```yaml
media_lights_sync:
  # ...
  use_current_brightness: True
```
in order to not change the brightness when the colors are changing.

Just let me know what you think of it, and I will publish a new release with that feature.

Regards,

**Comment by ericmatte** [comment]
@thundergreen btw, are you using this app with Kodi?

If so, just let me know so I can add it to my compatibility list if it is working great for you :)
