### ISSUE TITLE
[Feature Request] adding camera entity to geet pictures

### ISSUE THREAD

**Issue by thundergreen** [ericmatte/ad-media-lights-sync#51]
Hello,

I have Hyperion running for my ambilight. This platform adds a camera with the actual picture processed by ambilight. This updates the picture much faster than the 10 seconds of media player.
Would it be possible to use camera iso media_player?

Seems working but possible to decrease the intervall to scan?

Problem with cam is that the url does not change. Media_player seems changing the url?

Maybe it would be nice having a way to pull / update the pic to proceed every x seconds?

**Comment by ericmatte** [comment]
Hi @thundergreen,

Like you said: The app listen for url changes in order to update the lights.

For a camera to work with it, it would need an interval scan, and that would be a completely different approach, but yes, it could be possible. 

We could add two new fields in the configuration file like so:
```yaml
cameras:
  - camera_one
camera_scan_interval: 3 # in seconds
```

While I currently don't have a use case for that, I would be open to a pull request if you want.

**Comment by thundergreen** [comment]
Hello well I dont know how to change the code .would like to test this
indeed if ,ou would add this

What do you think ?

Eric Matte ***@***.***> schrieb am Do., 25. Aug. 2022, 19:44:

**Comment by ericmatte** [comment]
Closing due to inactivy, and as I don't plan to write this feature in the near future. Feel free to reopen if needed.
