### ISSUE TITLE
rgbww_color mode support

### ISSUE THREAD

**Issue by ckholy2** [ericmatte/ad-media-lights-sync#55]
Support of rgbww_color mode instead of only rgb_color mode

I found this app only support rgb_color mode.
Unfortunately, some of Wiz lights cannot convert rgb_color to rgbww_color correctly.

I think more and more rgbww_color product will be in the market, is it possible to support rgbww_color if specified in app.yaml?
Thanks.

**Comment by ericmatte** [comment]
Hi @ckholy2, unfortunately I don't have any `rgbww_color` to test this.

I have however a `rgbw_color` light, and it supports `rgb_color` as well without any problem:

![CleanShot 2023-01-04 at 22 24 58](https://user-images.githubusercontent.com/9013072/210695122-f4a046b7-ea7d-4d3f-8016-343c5dc5a466.png)

What you could test would be to change the attribute here for `rgbww_color`:

https://github.com/ericmatte/ad-media-lights-sync/blob/453d6b7ba4d76c08ec4c0c017d20a06a9d621fbc/apps/media_lights_sync/media_lights_sync.py#L108

Add add the two `ww` values in the `get_colors()` method, so that it would return `[#, #, #, #, 0, 0]` instead of `[#, #, #, #]`.

**Comment by ericmatte** [comment]
Closed due to innactivity. Feel free to reopen the issue if needed.
